# http://www.keycloak.org/docs/latest/server_admin/topics/export-import.html
apiVersion: batch/v1
kind: Job
metadata:
  name: kc-export
  namespace: keycloak
spec:
  template:
    metadata:
      labels:
        app: keycloak-export
    spec:
      containers:
      - name: keycloak-ha
        image: jboss/keycloak:3.3.0.Final@sha256:b89ee37d56f8da62c6844dd58d1a1dff5904df675536b7c075243cfc6ffeb7ca
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql.mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: keycloak
        - name: MYSQL_USER
          value: keycloak_readonly
        - name: MYSQL_PASSWORD
          value: keycloak_readonly
        command:
        - /bin/bash
        - -c
        - >
          /opt/jboss/docker-entrypoint.sh
          -Dkeycloak.migration.action=export
          -Dkeycloak.migration.provider=dir
          -Dkeycloak.migration.dir=/tmp
      restartPolicy: Never
  backoffLimit: 2
